### ISSUE TITLE
 'USER STORY: Documentation'

### ISSUE THREAD

**Issue by Filmon-gh** [Filmon-gh/aquapulse-haven#10]
As a **developer** I can**enhance the README documentation** so that**to fulfill all assessment criteria.**

# Acceptance Criteria
 - The README includes additional sections covering Technologies utilized, Deployment instructions,  Code and Media Credits, and Acknowledgements.
 -  Ensure there are no grammatical or spelling errors.

 
# Tasks
 - [ ] Enhance the README by providing detailed and clear documentation of the project works.
 - [ ]  Check and confirm the functionality of all links within the README.
 - [ ] Perform comprehensive proofreading of the README to identify and correct any grammar and spelling mistakes.
