### ISSUE TITLE
 'USER STORY: Make a Reservation'

### ISSUE THREAD

**Issue by Filmon-gh** [Filmon-gh/aquapulse-haven#7]
As a **customer of River Picnic Adventure**  I can **able to make a reservation** so that **I can secure a spot for a riverside picnic experience**

# Acceptance Criteria
 - Booking requires user accounts.
 - User profiles must include essential information (name, email, phone).
 - Admins must have access to reservations for approval in the backend.
 - Users should view reservation status in their profiles.

# Tasks
 - [ ] Develop the reservation model for backend functionality).
 - [ ] Design and implement the reservation form.
 - [ ] Integrate reservation details into user profiles.
 - [ ] Implement user confirmation upon reservation acceptance.
 - [ ] Implement user notifications in case of non-acceptance of reservations
