### ISSUE TITLE
 'USER STORY: Testing'

### ISSUE THREAD

**Issue by Filmon-gh** [Filmon-gh/aquapulse-haven#8]
As a **developer**  I can **perform website testing** so that **the final product is error-free and ready for a successful launch.**
 
# Acceptance Criteria
 - Acceptance Criteria 1 :
 - Acceptance Criteria 2 :
 - Acceptance Criteria 3 :
 
# Tasks
 - [ ] Backend logic and code should undergo thorough error-free testing.
 - [ ] Frontend HTML and CSS must be error-free after testing.
 - [ ] Ensure all links are functional and lead to the correct actions.
 - [ ] Ensure images and aesthetic content are displayed clearly and user-friendly.
 - [ ] The website should achieve a high score on Google Lighthouse.
 - [ ] The deployed website should perform as expected on partner hosting.
 - [ ] Document all tests in the readme, either directly or in a dedicated tests file.
